export const THREATS = [
  {
    id: 1,
    type: "SQL INJECTION",
    severity: "CRITICAL",
    data: [
      { label: "Source IP", value: "192.168.4.221" },
      { label: "Target",    value: "auth-db.prod" },
      { label: "Vector",    value: "Query param ?id=" },
    ],
    logs: [
      "GET /login?id=1' OR '1'='1 HTTP/1.1",
      "[DB]  Syntax error near OR '1'='1",
      "[WAF] Alert: SQLi pattern match #4471",
    ],
    correct: "Block & sanitize input",
    options: ["Block & sanitize input","Rate-limit the endpoint","Rotate DB credentials","Log and monitor only"],
    explanation: "SQLi requires immediate input sanitization and parameterized queries. Logging alone lets the attacker keep trying.",
  },
  {
    id: 2,
    type: "RANSOMWARE C2",
    severity: "CRITICAL",
    data: [
      { label: "Beacon",    value: "185.220.101.47:443" },
      { label: "Process",   value: "svchost.exe" },
      { label: "Encrypted", value: "YES — AES-256 stream" },
    ],
    logs: [
      "[NET] Abnormal DNS: *.onion resolved",
      "[EDR] svchost.exe spawned cmd.exe",
      "[NET] AES-256 stream to 185.220.101.47:443",
    ],
    correct: "Isolate host immediately",
    options: ["Isolate host immediately","Block outbound port 443","Restart the service","Patch the OS"],
    explanation: "Active C2 channel means ransomware is staging. Host isolation prevents lateral spread and key exfiltration.",
  },
  {
    id: 3,
    type: "PHISHING — EXEC",
    severity: "HIGH",
    data: [
      { label: "From",       value: "hr-payroll@c0mpany.net" },
      { label: "Attachment", value: "Q4_Bonus.xls.exe" },
      { label: "User click", value: "YES" },
    ],
    logs: [
      "[MAIL] Spoofed header detected",
      "[EDR]  .xls.exe executed in %TEMP%",
      "[NET]  LDAP enumeration began post-exec",
    ],
    correct: "Kill process & isolate",
    options: ["Kill process & isolate","Delete the email","Warn the user","Block sender domain"],
    explanation: "Post-exec LDAP enumeration means the payload is already running AD recon. Process termination + isolation is the only safe response.",
  },
  {
    id: 4,
    type: "STEALTH PORT SCAN",
    severity: "MEDIUM",
    data: [
      { label: "Source",    value: "10.0.3.88" },
      { label: "Scan type", value: "SYN stealth (half-open)" },
      { label: "Ports",     value: "22, 80, 443, 3306, 5432" },
    ],
    logs: [
      "[FW]  450 SYN packets in 2 seconds",
      "[IDS] Nmap OS fingerprint detected",
      "[NET] TTL anomaly — spoofed source likely",
    ],
    correct: "Block source & alert",
    options: ["Block source & alert","Close open ports","Ignore — normal traffic","Increase firewall rules"],
    explanation: "SYN stealth scans are pre-attack reconnaissance. Blocking the source and alerting SOC prevents follow-on exploitation.",
  },
  {
    id: 5,
    type: "BRUTE FORCE LOGIN",
    severity: "HIGH",
    data: [
      { label: "Target",   value: "admin@portal.internal" },
      { label: "Attempts", value: "842 in 60 seconds" },
      { label: "Tool sig", value: "Hydra/9.3" },
    ],
    logs: [
      "[AUTH] 842 failed SSH logins from 203.0.113.44",
      "[IDS]  Hydra user-agent fingerprint matched",
      "[NET]  Single source — not distributed",
    ],
    correct: "Lock account & ban IP",
    options: ["Lock account & ban IP","Force password reset","Enable 2FA now","Notify the user only"],
    explanation: "Account lockout stops the brute force immediately. IP ban prevents pivot to other accounts.",
  },
  {
    id: 6,
    type: "LATERAL MOVEMENT",
    severity: "CRITICAL",
    data: [
      { label: "Path",   value: "WS-014 → DC-01" },
      { label: "Method", value: "Pass-the-Hash (NTLM)" },
      { label: "Time",   value: "03:17 UTC — off-hours" },
    ],
    logs: [
      "[AD]  Unusual admin login from WS-014",
      "[EDR] mimikatz signature detected",
      "[AD]  DC-01 accessed — domain controller",
    ],
    correct: "Revoke tokens & isolate",
    options: ["Revoke tokens & isolate","Reset all passwords","Monitor for now","Patch SMB protocol"],
    explanation: "DC compromise = game over if not contained. Token revocation kills active sessions instantly.",
  },
  {
    id: 7,
    type: "ZERO-DAY EXPLOIT",
    severity: "CRITICAL",
    data: [
      { label: "CVE",    value: "UNKNOWN — no signature" },
      { label: "Target", value: "nginx/1.18.0" },
      { label: "Shell",  value: "Reverse shell active" },
    ],
    logs: [
      "[WAF] Anomalous payload — zero sig matches",
      "[EDR] nginx spawned /bin/sh (unexpected)",
      "[NET] Reverse shell → 198.51.100.9:4444",
    ],
    correct: "Terminate & patch nginx",
    options: ["Terminate & patch nginx","Update WAF rules only","Restart web server","Alert vendor only"],
    explanation: "An active reverse shell means RCE. Kill nginx immediately, apply the patch before bringing it back.",
  },
  {
    id: 8,
    type: "INSIDER THREAT",
    severity: "HIGH",
    data: [
      { label: "User",    value: "j.morris@corp" },
      { label: "Action",  value: "48 GB exported to USB" },
      { label: "Context", value: "On PIP — 23:44 local time" },
    ],
    logs: [
      "[DLP]  Mass export: /finance/Q4/* to USB",
      "[HR]   User on Performance Improvement Plan",
      "[SIEM] After-hours access anomaly flagged",
    ],
    correct: "Revoke access immediately",
    options: ["Revoke access immediately","Interview the user first","Monitor activity","Increase DLP sensitivity"],
    explanation: "Data is already exfiltrated. Immediate access revocation prevents further damage and preserves evidence.",
  },
  {
    id: 9,
    type: "DNS HIJACK",
    severity: "HIGH",
    data: [
      { label: "Domain",    value: "internal.corp.net" },
      { label: "Rogue DNS", value: "192.0.2.1 (external)" },
      { label: "SSL",       value: "Cert mismatch detected" },
    ],
    logs: [
      "[DNS] SOA record modified externally",
      "[NET] Internal queries leaking to internet",
      "[SSL] Cert CN mismatch on internal.corp.net",
    ],
    correct: "Restore DNS & audit records",
    options: ["Restore DNS & audit records","Flush DNS cache only","Block rogue IP","Reboot DNS server"],
    explanation: "The authoritative record is poisoned. Cache flush is temporary — you must restore the SOA record and audit all DNS changes.",
  },
  {
    id: 10,
    type: "SUPPLY CHAIN ATTACK",
    severity: "CRITICAL",
    data: [
      { label: "Package",  value: "lodash@4.17.21-patch" },
      { label: "Pipeline", value: "CI/CD run #334 — deployed" },
      { label: "Backdoor", value: "Callback to cdn-analytics.io" },
    ],
    logs: [
      "[CI]  Hash mismatch on lodash bundle vs registry",
      "[EDR] Backdoor callback post-deploy detected",
      "[NET] Data exfil to cdn-analytics.io:443",
    ],
    correct: "Rollback & audit pipeline",
    options: ["Rollback & audit pipeline","Remove the package only","Scan with antivirus","Block external CDN"],
    explanation: "Tampered dependency is in production. Rollback immediately, audit the entire CI/CD pipeline.",
  },
  {
    id: 11,
    type: "DDoS — UDP FLOOD",
    severity: "HIGH",
    data: [
      { label: "Volume",   value: "94 Gbps inbound" },
      { label: "Protocol", value: "UDP flood — port 53" },
      { label: "Botnet",   value: "~12,000 nodes" },
    ],
    logs: [
      "[NET] 94 Gbps UDP flood to port 53",
      "[ISP] BGP route anomaly upstream",
      "[SRV] Load balancer CPU at 100%",
    ],
    correct: "Enable DDoS scrubbing",
    options: ["Enable DDoS scrubbing","Restart load balancer","Block UDP globally","Scale up servers"],
    explanation: "At 94 Gbps you cannot block at server level — you need upstream scrubbing to absorb the volume.",
  },
  {
    id: 12,
    type: "CREDENTIAL STUFFING",
    severity: "MEDIUM",
    data: [
      { label: "Target",     value: "/api/v2/auth" },
      { label: "Rate",       value: "12,000 req/min" },
      { label: "Match rate", value: "3.2% — known breach list" },
    ],
    logs: [
      "[API]  Rate anomaly: 12k req/min from distributed IPs",
      "[AUTH] 384 successful logins — all new geolocations",
      "[INTEL] Source IPs on known breach watchlist",
    ],
    correct: "Enable CAPTCHA & invalidate sessions",
    options: ["Enable CAPTCHA & invalidate sessions","Reset all passwords globally","Block API endpoint","Monitor only"],
    explanation: "Accounts are actively being taken over. CAPTCHA stops automation; session invalidation kicks out attackers.",
  },
  {
    id: 13,
    type: "ARP SPOOFING",
    severity: "HIGH",
    data: [
      { label: "Attacker", value: "10.0.0.44 (rogue)" },
      { label: "Method",   value: "Gratuitous ARP flood" },
      { label: "Target",   value: "Default gateway 10.0.0.1" },
    ],
    logs: [
      "[NET] Duplicate ARP replies for 10.0.0.1",
      "[IDS] Gratuitous ARP flood from 10.0.0.44",
      "[NET] Traffic redirected — MITM in progress",
    ],
    correct: "Enable dynamic ARP inspection",
    options: ["Enable dynamic ARP inspection","Reboot the gateway","Block ICMP traffic","Segment the VLAN"],
    explanation: "Dynamic ARP Inspection validates ARP packets against a DHCP snooping table to drop rogue replies.",
  },
  {
    id: 14,
    type: "CRYPTOJACKING",
    severity: "MEDIUM",
    data: [
      { label: "Host",     value: "web-prod-03" },
      { label: "CPU",      value: "97% sustained — xmrig" },
      { label: "Outbound", value: "pool.minexmr.com:3333" },
    ],
    logs: [
      "[EDR] xmrig process spawned via cron job",
      "[NET] Persistent connection to mining pool",
      "[SYS] web-prod-03 CPU 97% for 6+ hours",
    ],
    correct: "Kill process & audit cron",
    options: ["Kill process & audit cron","Reboot the server","Block mining pool IP","Throttle CPU usage"],
    explanation: "Kill xmrig immediately, then audit cron/startup scripts for persistence. Rebooting alone won't remove the cron job.",
  },
  {
    id: 15,
    type: "KERBEROASTING",
    severity: "CRITICAL",
    data: [
      { label: "Account", value: "svc_backup (SPN set)" },
      { label: "Method",  value: "TGS ticket requested" },
      { label: "Hash",    value: "RC4 — offline crack target" },
    ],
    logs: [
      "[AD]  Unusual TGS request for svc_backup",
      "[EDR] Impacket GetUserSPNs.py signature",
      "[AD]  RC4 downgrade negotiated — weak cipher",
    ],
    correct: "Rotate SPN password & use AES",
    options: ["Rotate SPN password & use AES","Disable the account","Block RC4 system-wide","Reset all AD passwords"],
    explanation: "Immediate password rotation invalidates the stolen ticket. Migrating to AES prevents future RC4 downgrade attacks.",
  },
]

export const DIFF_CONFIG = {
  ROOKIE:   { time: 90, qTime: 20, lives: 5, color: "#00ff88" },
  OPERATOR: { time: 60, qTime: 13, lives: 3, color: "#ffcc00" },
  PHANTOM:  { time: 45, qTime:  8, lives: 2, color: "#ff3355" },
}